services:
  api:
    container_name: lang-api
    build:
      context: .
    ports:
      - "${APP_PORT}:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    profiles: ["prod"]

  api-dev:
    container_name: lang-api-dev
    build:
      context: .
    ports:
      - "${RELOAD_PORT}:8000"
    volumes:
      - ./app:/app/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    profiles: ["dev"]
